version: "3"
services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    build: 
      context: ./environment/docker/mysql5.6/
      args:
        - VERSION=${VERSION}
        - DOMAIN=${DOMAIN}
        - EMAIL=${EMAIL}
    image: ${DB_CONTAINER_IMAGE}
    networks:
      nat:
        ipv4_address: ${DB_CONTAINER_IP}
networks:
  nat:
    ipam:
      config:
      - subnet: ${SUBNET}