version: "3"
services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    build: 
      context: ./environment/docker/mysql5.6/
      args:
        - VERSION=${VERSION}
        - DOMAIN=${DOMAIN}
        - EMAIL=${EMAIL}
    image: ${DB_CONTAINER_IMAGE}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      nat:
        ipv4_address: ${DB_CONTAINER_IP}
  phpmyadmin:
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    build: 
      context: ./environment/docker/phpmyadmin
      args:
        - 'VERSION=${VERSION}'
        - 'DOMAIN=${DOMAIN}'
        - 'EMAIL=${EMAIL}'
    image: ${PHPMYADMIN_CONTAINER_IMAGE}
    links:
      - db
    environment:
      PMA_HOST: ${DB_CONTAINER_IP}
      PMA_PORT: ${DB_CONTAINER_PORT}
    networks:
      nat:
        ipv4_address: ${PHPMYADMIN_CONTAINER_IP}
  web:
    container_name: ${WEB_CONTAINER_NAME}
    build: ./environment/docker/php7.2/
    image: ${WEB_CONTAINER_IMAGE}
    volumes:
      - ./:/var/www/html
      - ./environment/etc/apache2/vhosts:/etc/apache2/sites-enabled
      - ./environment/etc/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - APACHE_DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}
      - DOMAIN=${DOMAIN}    
    networks:
      nat:
        ipv4_address: ${WEB_CONTAINER_IP}
networks:
  nat:
    ipam:
      config:
      - subnet: ${SUBNET}